#!/usr/bin/env bash
set -Eeuo pipefail

# Prefer the Git repository that contains the current working directory. This
# keeps the collector usable even when the script is streamed/copied to /tmp.
if ROOT="$(git -C "$PWD" rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  if ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
    :
  else
    printf 'ERROR: run this script from inside the nitro-an14-41-debian Git repository.\n' >&2
    exit 1
  fi
fi

OUT="$ROOT/snapshot/current"
mkdir -p "$OUT/config"

safe_copy() {
  local src="$1" dst="$2"
  [[ -f "$src" ]] || return 0
  if grep -Eq '://[^/[:space:]]+:[^/@[:space:]]+@' "$src" 2>/dev/null; then
    echo "SKIPPED possible embedded credential: $src" >> "$OUT/SKIPPED.txt"
    return 0
  fi
  install -D -m 0644 "$src" "$OUT/config/$dst"
}

{
  echo "captured=$(date --iso-8601=seconds)"
  echo "kernel=$(uname -r)"
  . /etc/os-release
  echo "os=${PRETTY_NAME:-unknown}"
  echo "product=$(cat /sys/class/dmi/id/product_name 2>/dev/null || true)"
  echo "bios=$(cat /sys/class/dmi/id/bios_version 2>/dev/null || true)"
} > "$OUT/system.txt"

apt-mark showmanual | sort > "$OUT/apt-manual.txt"
apt-mark showhold | sort > "$OUT/apt-holds.txt"
dpkg-query -W -f='${binary:Package}\t${Version}\t${Architecture}\n' | sort > "$OUT/dpkg-versions.tsv"
dkms status > "$OUT/dkms.txt" 2>&1 || true
swapon --show > "$OUT/swap.txt" 2>&1 || true
zramctl > "$OUT/zram.txt" 2>&1 || true
powerprofilesctl get > "$OUT/power-profile.txt" 2>&1 || true
systemctl list-unit-files --state=enabled --no-pager > "$OUT/systemd-enabled.txt" 2>&1 || true
systemctl --user list-unit-files --state=enabled --no-pager > "$OUT/systemd-user-enabled.txt" 2>&1 || true
kscreen-doctor -o > "$OUT/display.txt" 2>&1 || true
vulkaninfo --summary > "$OUT/vulkan.txt" 2>&1 || true
glxinfo -B > "$OUT/opengl.txt" 2>&1 || true

{
  echo '=== sources ==='
  grep -RhvE '^[[:space:]]*(#|$)' /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null || true
  echo
  echo '=== preferences ==='
  grep -Rh . /etc/apt/preferences /etc/apt/preferences.d/* 2>/dev/null || true
} | sed -E 's#(https?://)[^/@[:space:]]+:[^/@[:space:]]+@#\1REDACTED@#g' > "$OUT/apt-repositories.txt"

safe_copy /etc/gamemode.ini etc/gamemode.ini
safe_copy /etc/systemd/zram-generator.conf etc/systemd/zram-generator.conf
safe_copy /etc/default/grub etc/default/grub
safe_copy /etc/systemd/system/asense-keyboard-warm.service etc/systemd/system/asense-keyboard-warm.service
safe_copy /usr/local/sbin/asense-keyboard-warm usr/local/sbin/asense-keyboard-warm
safe_copy /usr/local/bin/gamemode-profile-start usr/local/bin/gamemode-profile-start
safe_copy /usr/local/bin/gamemode-profile-end usr/local/bin/gamemode-profile-end

if command -v pipx >/dev/null 2>&1; then
  pipx list > "$OUT/pipx.txt" 2>&1 || true
fi

if command -v flatpak >/dev/null 2>&1; then
  flatpak list --app --columns=application,branch,origin > "$OUT/flatpak-apps.tsv" 2>&1 || true
fi

{
  for dir in "$HOME/.steam/root/compatibilitytools.d" "$HOME/.local/share/Steam/compatibilitytools.d"; do
    [[ -d "$dir" ]] || continue
    echo "$dir"
    find "$dir" -mindepth 1 -maxdepth 1 -type d -printf '  %f\n' | sort
  done
} > "$OUT/steam-compatibility-tools.txt"

if [[ -x "$HOME/.openclaw/bin/openclaw" ]]; then
  "$HOME/.openclaw/bin/openclaw" --version > "$OUT/openclaw-version.txt" 2>&1 || true
fi
if [[ -f "$HOME/.openclaw/workspace/AGENTS.md" ]]; then
  install -m 0644 "$HOME/.openclaw/workspace/AGENTS.md" "$OUT/openclaw-AGENTS.md"
fi

cat > "$OUT/README.md" <<'TXT'
# Sanitized current-system snapshot

Generated by `scripts/capture-system.sh`.

This snapshot intentionally does **not** copy credentials, browser profiles,
SSH/GPG keys, VPN configuration, password stores, OpenClaw authentication,
Steam/Heroic credentials, `.env` files, or arbitrary home-directory content.

It is an audit/reference snapshot. The actual rebuild logic lives in
`bootstrap/` and applies the validated configuration declaratively.
TXT

printf 'Snapshot written to %s\n' "$OUT"
printf 'Review before committing: git diff -- snapshot/current\n'
